{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "minio.name" . }}
    helm.sh/chart: {{ include "minio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.accessKey.password }}
  access-key: {{ .Values.accessKey.password | b64enc }}
  {{- else if (not .Values.accessKey.forcePassword) }}
  access-key: {{ randAlphaNum 10 | b64enc }}
  {{- else }}
  access-key: {{ required "An Access Key is required!" .Values.accessKey.password }}
  {{- end }}
  {{- if .Values.secretKey.password }}
  secret-key: {{ .Values.secretKey.password | b64enc }}
  {{- else if (not .Values.secretKey.forcePassword) }}
  secret-key: {{ randAlphaNum 40 | b64enc }}
  {{- else }}
  secret-key: {{ required "A Secret Key is required!" .Values.secretKey.password }}
  {{- end }}
{{- end }}
