{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "minio.serviceAccountName" . }}
  labels: {{- include "minio.labels" . | nindent 4 }}
secrets:
  - name: {{ include "minio.fullname" . }}
{{- end }}
